# see: https://github.com/marketplace/actions/test-compile-for-arduino

name: build
on: [push, pull_request]
jobs:
  build:
    name: build for MCU
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install ESP-IDF dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

    - name: Clone ESP-IDF v5.4
      run: |
        git clone --depth 1 https://github.com/espressif/esp-idf.git -b v5.4
        cd esp-idf
        ./install.sh esp32s3
          
    - name: Set up ESP-IDF environment
      run: |
        cd esp-idf
        . ./export.sh

    - name: Install Arduino ESP32 core (version 3.1.2)
      run: |
        mkdir -p ~/arduino-esp32
        cd ~/arduino-esp32
        git clone --depth 1 -b 3.1.2 https://github.com/espressif/arduino-esp32.git .
        git submodule update --init --recursive
        cd tools
        python3 get.py
          
    - name: Checkout NMEA2000 library
      uses: actions/checkout@v4
      with:
          repository: ttlappalainen/NMEA2000
          ref: master
          path: CustomLibrary_NMEA2000 # must contain string "Custom"

    - name: Compile Arduino sketch for AtomS3 (ESP32-S3) with Hardware CDC
      run: |
        export ARDUINO_IDE_PATH=~/arduino-esp32
        export SKETCH_PATH=$GITHUB_WORKSPACE/bbn-m5-s3-n2k-usb
        cd $ARDUINO_IDE_PATH
        python3 tools/build.py -b esp32s3 -p $GITHUB_WORKSPACE --ide=arduino --build-property "build.usb_flags=-DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1"

    - name: Find versions
      run: |
        find /home/runner -name esptool\*
        find /home/runner -name boot_app0.bin
        ls -la /home/runner/
        ls -l /home/runner/.arduino15/packages/esp32/tools/esptool_py/*

    - name: Make merged .bin
      run: |
        cd $GITHUB_WORKSPACE/build
        esptool.py \
        --chip esp32s3 merge_bin -o bbn-m5-s3-n2k-usb_firmware.bin \
        --flash_mode dio --flash_freq 80m --flash_size 4MB 
        0x0 bbn-m5-s3-n2k-usb.ino.bootloader.bin \
        0x8000 bbn-m5-s3-n2k-usb.ino.partitions.bin \
        0xe000 "$HOME/.arduino15/packages/esp32/hardware/esp32/3.1.2/tools/partitions/boot_app0.bin" \
        0x10000 bbn-m5-s3-n2k-usb.ino.bin 

    - name: Make zip
      run: |
        ls /home/runner/work/bbn-m5-s3-n2k-usb/bbn-m5-s3-n2k-usb/build/*.bin /home/runner/work/bbn-m5-s3-n2k-usb/bbn-m5-s3-n2k-usb/build/*.csv | zip bbn-m5-s3-n2k-usb_bin-$(date +%Y-%m-%d).zip -j -@
        pwd
        ls *.zip
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bbn-m5-s3-n2k-usb_bin*.zip
        tag: ${{ github.ref == 'refs/heads/main' && 'vTest' || github.ref }}
        overwrite: true
        file_glob: true
