name: Build Arduino Sketch for M5Stack AtomS3 with ESP-IDF 5.4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install ESP-IDF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

      - name: Clone ESP-IDF v5.4
        run: |
          git clone --recursive https://github.com/espressif/esp-idf.git -b v5.4
          cd esp-idf
          ./install.sh

      - name: Set up ESP-IDF environment
        run: |
          cd esp-idf
          . ./export.sh

      - name: Install Arduino ESP32 core (version 3.1.2)
        run: |
          mkdir -p ~/arduino-esp32
          cd ~/arduino-esp32
          git clone https://github.com/espressif/arduino-esp32.git .
          git checkout 3.1.2
          git submodule update --init --recursive
          cd tools
          python3 get.py

      - name: Install M5Unified library
        run: |
          mkdir -p ~/Arduino/libraries
          cd ~/Arduino/libraries
          git clone https://github.com/m5stack/M5Unified.git

      - name: Compile Arduino sketch for AtomS3 (ESP32-S3) with Hardware CDC
        run: |
          export ARDUINO_IDE_PATH=~/arduino-esp32
          export SKETCH_PATH=$GITHUB_WORKSPACE/YourSketchName.ino
          cd $ARDUINO_IDE_PATH
          python3 tools/build.py -b esp32s3 -p $GITHUB_WORKSPACE --ide=arduino --build-property "build.usb_flags=-DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1"

      - name: Merge binaries with esptool
        run: |
          cd $GITHUB_WORKSPACE/build
          esptool.py --chip esp32s3 merge_bin -o merged_firmware.bin \
          --flash_mode dio --flash_freq 80m --flash_size 4MB \
          0x1000 bootloader.bin \
          0x8000 partition-table.bin \
          0x10000 YourSketchName.ino.bin

      - name: Upload merged binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: merged_firmware.bin
          path: $GITHUB_WORKSPACE/build/merged_firmware.bin
